'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    'NOTA: este archivo se genera de forma automática; no lo modifique directamente. Para realizar cambios,
    ' o si detecta errores de compilación en este archivo, vaya al Diseñador de proyectos
    ' (vaya a Propiedades del proyecto o haga doble clic en el nodo My Project en el
    ' Explorador de soluciones) y realice cambios en la pestaña Aplicación.
    '
    Partial Friend Class MyApplication
        
        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = false
            Me.EnableVisualStyles = true
            Me.SaveMySettingsOnExit = true
            Me.ShutDownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterAllFormsClose
        End Sub
        
        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Protected Overrides Sub OnCreateMainForm()
<<<<<<< HEAD
            Me.MainForm = Global._2024CompuAplicada_PF.frmMenuPrincipal
=======
<<<<<<< HEAD
            Me.MainForm = Global._2024CompuAplicada_PF.mdiOperador
=======
<<<<<<< HEAD
            Me.MainForm = Global._2024CompuAplicada_PF.frmmenuprincipal
=======
            Me.MainForm = Global._2024CompuAplicada_PF.mdiAdministrador
>>>>>>> 0a739eeee4209a0a94e104771d665aa3da5e2af6
>>>>>>> 7ac0872d42d1709f57157b12b28e4c8e3ba3243d
>>>>>>> 49f8d7f1557077b19bbb7bc8954c41ac268b2028
        End Sub
    End Class
End Namespace
